INSERT INTO LERNKARTE (LERNKARTENID, LERNKARTENNAME, LERNKARTENFRAGE, LERNKARTENANTWORT, LERNKARTENMODUL, LERNKARTEUEBERPRUEFT)
VALUES (1, 'SE-Lernkarte01', 'WELCHE FARBE HAT MEINE UNTERHOSE?', 'Weiﬂ', 'SE', 'false');

INSERT INTO LERNKARTE (LERNKARTENID, LERNKARTENNAME, LERNKARTENFRAGE, LERNKARTENANTWORT, LERNKARTENMODUL, LERNKARTEUEBERPRUEFT)
VALUES (2, 'SE-Lernkarte02', 'WELCHE FARBE hat mein tshirt?', 'Rot', 'SE', 'false');

INSERT INTO LERNKARTE (LERNKARTENID, LERNKARTENNAME, LERNKARTENFRAGE, LERNKARTENANTWORT, LERNKARTENMODUL, LERNKARTEUEBERPRUEFT)
VALUES (3, 'BS-Lernkarte01', 'Was ist ein MUTEX?', 'Wissen wir nicht', 'BS', 'false');
